import type {
  PropertyCategory,
  PropertySchema,
} from "@/types/schema";

function titleCategory(): PropertyCategory {
  return {
    id: "title",
    label: "Title",
    icon: "heading",
    description: "Chart title configuration",
    properties: [
      {
        path: "title.text",
        key: "text",
        label: "Text",
        description: "Main title text",
        category: "title",
        inputType: "string",
        defaultValue: "",
      },
      {
        path: "title.subtext",
        key: "subtext",
        label: "Subtext",
        description: "Subtitle text",
        category: "title",
        inputType: "string",
        defaultValue: "",
      },
      {
        path: "title.left",
        key: "left",
        label: "Left",
        description: "Horizontal position of title",
        category: "title",
        inputType: "enum",
        defaultValue: "center",
        enumValues: ["left", "center", "right", "auto"],
      },
      {
        path: "title.top",
        key: "top",
        label: "Top",
        description: "Vertical position of title",
        category: "title",
        inputType: "enum",
        defaultValue: "auto",
        enumValues: ["top", "middle", "bottom", "auto"],
      },
      {
        path: "title.textStyle.color",
        key: "color",
        label: "Text Color",
        description: "Title text color",
        category: "title",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "title.textStyle.fontSize",
        key: "fontSize",
        label: "Font Size",
        description: "Title font size in pixels",
        category: "title",
        inputType: "number",
        defaultValue: 18,
        min: 10,
        max: 72,
      },
      {
        path: "title.textStyle.fontWeight",
        key: "fontWeight",
        label: "Font Weight",
        description: "Title font weight",
        category: "title",
        inputType: "enum",
        defaultValue: "bold",
        enumValues: ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"],
      },
      {
        path: "title.textAlign",
        key: "textAlign",
        label: "Text Align",
        description: "Text alignment within title block",
        category: "title",
        inputType: "enum",
        defaultValue: "auto",
        enumValues: ["auto", "left", "center", "right"],
      },
      {
        path: "title.backgroundColor",
        key: "backgroundColor",
        label: "Background Color",
        description: "Title background color",
        category: "title",
        inputType: "color",
        defaultValue: "transparent",
      },
      {
        path: "title.borderWidth",
        key: "borderWidth",
        label: "Border Width",
        description: "Title border width in pixels",
        category: "title",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 20,
      },
      {
        path: "title.borderColor",
        key: "borderColor",
        label: "Border Color",
        description: "Title border color",
        category: "title",
        inputType: "color",
        defaultValue: "#ccc",
      },
      {
        path: "title.padding",
        key: "padding",
        label: "Padding",
        description: "Title padding in pixels",
        category: "title",
        inputType: "number",
        defaultValue: 5,
        min: 0,
        max: 50,
      },
    ],
  };
}

function tooltipCategory(): PropertyCategory {
  return {
    id: "tooltip",
    label: "Tooltip",
    icon: "info",
    description: "Tooltip configuration",
    properties: [
      {
        path: "tooltip.show",
        key: "show",
        label: "Show",
        description: "Whether to show tooltip",
        category: "tooltip",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "tooltip.trigger",
        key: "trigger",
        label: "Trigger",
        description: "How tooltip is triggered",
        category: "tooltip",
        inputType: "enum",
        defaultValue: "item",
        enumValues: ["item", "axis", "none"],
      },
      {
        path: "tooltip.axisPointer.type",
        key: "axisPointerType",
        label: "Axis Pointer Type",
        description: "Type of axis pointer for tooltip",
        category: "tooltip",
        inputType: "enum",
        defaultValue: "line",
        enumValues: ["line", "shadow", "cross", "none"],
      },
      {
        path: "tooltip.axisPointer.label.backgroundColor",
        key: "axisPointerLabelBg",
        label: "Pointer Label Background",
        description: "Axis pointer label background color",
        category: "tooltip",
        inputType: "color",
        defaultValue: "rgba(50,50,50,0.7)",
      },
      {
        path: "tooltip.backgroundColor",
        key: "backgroundColor",
        label: "Background Color",
        description: "Tooltip background color",
        category: "tooltip",
        inputType: "color",
        defaultValue: "rgba(50,50,50,0.9)",
      },
      {
        path: "tooltip.borderColor",
        key: "borderColor",
        label: "Border Color",
        description: "Tooltip border color",
        category: "tooltip",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "tooltip.borderWidth",
        key: "borderWidth",
        label: "Border Width",
        description: "Tooltip border width",
        category: "tooltip",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 10,
      },
      {
        path: "tooltip.textStyle.color",
        key: "textStyleColor",
        label: "Text Color",
        description: "Tooltip text color",
        category: "tooltip",
        inputType: "color",
        defaultValue: "#fff",
      },
      {
        path: "tooltip.textStyle.fontSize",
        key: "textStyleFontSize",
        label: "Text Size",
        description: "Tooltip text font size",
        category: "tooltip",
        inputType: "number",
        defaultValue: 14,
        min: 10,
        max: 24,
      },
      {
        path: "tooltip.formatter",
        key: "formatter",
        label: "Formatter",
        description: "Custom tooltip formatter function (JS expression string)",
        category: "tooltip",
        inputType: "function",
        defaultValue: undefined,
      },
      {
        path: "tooltip.padding",
        key: "padding",
        label: "Padding",
        description: "Tooltip padding in pixels",
        category: "tooltip",
        inputType: "number",
        defaultValue: 10,
        min: 0,
        max: 50,
      },
      {
        path: "tooltip.extraCssText",
        key: "extraCssText",
        label: "Extra CSS",
        description: "Extra CSS text for tooltip",
        category: "tooltip",
        inputType: "string",
        defaultValue: "",
      },
    ],
  };
}

function legendCategory(): PropertyCategory {
  return {
    id: "legend",
    label: "Legend",
    icon: "list",
    description: "Legend configuration",
    properties: [
      {
        path: "legend.show",
        key: "show",
        label: "Show",
        description: "Whether to show legend",
        category: "legend",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "legend.type",
        key: "type",
        label: "Type",
        description: "Legend display type",
        category: "legend",
        inputType: "enum",
        defaultValue: "scroll",
        enumValues: ["plain", "scroll"],
      },
      {
        path: "legend.orient",
        key: "orient",
        label: "Orientation",
        description: "Legend layout orientation",
        category: "legend",
        inputType: "enum",
        defaultValue: "horizontal",
        enumValues: ["horizontal", "vertical"],
      },
      {
        path: "legend.left",
        key: "left",
        label: "Left",
        description: "Horizontal position of legend",
        category: "legend",
        inputType: "enum",
        defaultValue: "center",
        enumValues: ["left", "center", "right", "auto"],
      },
      {
        path: "legend.top",
        key: "top",
        label: "Top",
        description: "Vertical position of legend",
        category: "legend",
        inputType: "enum",
        defaultValue: "auto",
        enumValues: ["top", "middle", "bottom", "auto"],
      },
      {
        path: "legend.textStyle.color",
        key: "textStyleColor",
        label: "Text Color",
        description: "Legend text color",
        category: "legend",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "legend.textStyle.fontSize",
        key: "textStyleFontSize",
        label: "Font Size",
        description: "Legend text font size",
        category: "legend",
        inputType: "number",
        defaultValue: 12,
        min: 8,
        max: 24,
      },
      {
        path: "legend.selectedMode",
        key: "selectedMode",
        label: "Selection Mode",
        description: "Whether legend items can be selected",
        category: "legend",
        inputType: "enum",
        defaultValue: "multiple",
        enumValues: ["multiple", "single", "false"],
      },
      {
        path: "legend.itemGap",
        key: "itemGap",
        label: "Item Gap",
        description: "Gap between legend items in pixels",
        category: "legend",
        inputType: "number",
        defaultValue: 10,
        min: 0,
        max: 50,
      },
      {
        path: "legend.itemWidth",
        key: "itemWidth",
        label: "Item Width",
        description: "Legend item width in pixels",
        category: "legend",
        inputType: "number",
        defaultValue: 25,
        min: 10,
        max: 100,
      },
      {
        path: "legend.itemHeight",
        key: "itemHeight",
        label: "Item Height",
        description: "Legend item height in pixels",
        category: "legend",
        inputType: "number",
        defaultValue: 14,
        min: 6,
        max: 50,
      },
    ],
  };
}

function gridCategory(): PropertyCategory {
  return {
    id: "grid",
    label: "Grid",
    icon: "grid",
    description: "Grid area configuration",
    properties: [
      {
        path: "grid.show",
        key: "show",
        label: "Show",
        description: "Whether to show the grid",
        category: "grid",
        inputType: "boolean",
        defaultValue: false,
      },
      {
        path: "grid.left",
        key: "left",
        label: "Left",
        description: "Left margin of grid (can be number or percentage)",
        category: "grid",
        inputType: "string",
        defaultValue: "10%",
      },
      {
        path: "grid.right",
        key: "right",
        label: "Right",
        description: "Right margin of grid",
        category: "grid",
        inputType: "string",
        defaultValue: "10%",
      },
      {
        path: "grid.top",
        key: "top",
        label: "Top",
        description: "Top margin of grid",
        category: "grid",
        inputType: "string",
        defaultValue: "10%",
      },
      {
        path: "grid.bottom",
        key: "bottom",
        label: "Bottom",
        description: "Bottom margin of grid",
        category: "grid",
        inputType: "string",
        defaultValue: "10%",
      },
      {
        path: "grid.width",
        key: "width",
        label: "Width",
        description: "Grid width",
        category: "grid",
        inputType: "string",
        defaultValue: "auto",
      },
      {
        path: "grid.height",
        key: "height",
        label: "Height",
        description: "Grid height",
        category: "grid",
        inputType: "string",
        defaultValue: "auto",
      },
      {
        path: "grid.containLabel",
        key: "containLabel",
        label: "Contain Label",
        description: "Whether grid includes axis labels",
        category: "grid",
        inputType: "boolean",
        defaultValue: false,
      },
      {
        path: "grid.backgroundColor",
        key: "backgroundColor",
        label: "Background Color",
        description: "Grid background color",
        category: "grid",
        inputType: "color",
        defaultValue: "transparent",
      },
      {
        path: "grid.borderColor",
        key: "borderColor",
        label: "Border Color",
        description: "Grid border color",
        category: "grid",
        inputType: "color",
        defaultValue: "#ccc",
      },
      {
        path: "grid.borderWidth",
        key: "borderWidth",
        label: "Border Width",
        description: "Grid border width",
        category: "grid",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 10,
      },
    ],
  };
}

function xAxisCategory(): PropertyCategory {
  return {
    id: "xAxis",
    label: "X Axis",
    icon: "axis-x",
    description: "X axis configuration",
    properties: [
      {
        path: "xAxis.type",
        key: "type",
        label: "Type",
        description: "X axis type",
        category: "xAxis",
        inputType: "enum",
        defaultValue: "category",
        enumValues: ["category", "value", "time", "log"],
      },
      {
        path: "xAxis.name",
        key: "name",
        label: "Name",
        description: "X axis name",
        category: "xAxis",
        inputType: "string",
        defaultValue: "",
      },
      {
        path: "xAxis.nameLocation",
        key: "nameLocation",
        label: "Name Location",
        description: "Position of axis name",
        category: "xAxis",
        inputType: "enum",
        defaultValue: "end",
        enumValues: ["start", "middle", "end"],
      },
      {
        path: "xAxis.nameTextStyle.color",
        key: "nameColor",
        label: "Name Color",
        description: "Axis name text color",
        category: "xAxis",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "xAxis.nameGap",
        key: "nameGap",
        label: "Name Gap",
        description: "Gap between name and axis",
        category: "xAxis",
        inputType: "number",
        defaultValue: 15,
        min: 0,
        max: 50,
      },
      {
        path: "xAxis.data",
        key: "data",
        label: "Data",
        description: "Category data array for category axis",
        category: "xAxis",
        inputType: "array",
        defaultValue: [],
      },
      {
        path: "xAxis.position",
        key: "position",
        label: "Position",
        description: "Position of x axis",
        category: "xAxis",
        inputType: "enum",
        defaultValue: "bottom",
        enumValues: ["top", "bottom"],
      },
      {
        path: "xAxis.offset",
        key: "offset",
        label: "Offset",
        description: "Offset of x axis from default position",
        category: "xAxis",
        inputType: "number",
        defaultValue: 0,
        min: -100,
        max: 100,
      },
      {
        path: "xAxis.min",
        key: "min",
        label: "Min",
        description: "Minimum value of axis",
        category: "xAxis",
        inputType: "string",
        defaultValue: "auto",
      },
      {
        path: "xAxis.max",
        key: "max",
        label: "Max",
        description: "Maximum value of axis",
        category: "xAxis",
        inputType: "string",
        defaultValue: "auto",
      },
      {
        path: "xAxis.splitNumber",
        key: "splitNumber",
        label: "Split Number",
        description: "Approximate number of splits",
        category: "xAxis",
        inputType: "number",
        defaultValue: 5,
        min: 0,
        max: 20,
      },
      {
        path: "xAxis.axisLabel.show",
        key: "axisLabelShow",
        label: "Show Labels",
        description: "Whether to show axis labels",
        category: "xAxis",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "xAxis.axisLabel.color",
        key: "axisLabelColor",
        label: "Label Color",
        description: "Axis label text color",
        category: "xAxis",
        inputType: "color",
        defaultValue: "#666",
      },
      {
        path: "xAxis.axisLabel.fontSize",
        key: "axisLabelFontSize",
        label: "Label Font Size",
        description: "Axis label font size",
        category: "xAxis",
        inputType: "number",
        defaultValue: 12,
        min: 8,
        max: 24,
      },
      {
        path: "xAxis.axisLabel.rotate",
        key: "axisLabelRotate",
        label: "Label Rotate",
        description: "Axis label rotation angle",
        category: "xAxis",
        inputType: "number",
        defaultValue: 0,
        min: -90,
        max: 90,
      },
      {
        path: "xAxis.axisLine.show",
        key: "axisLineShow",
        label: "Show Axis Line",
        description: "Whether to show axis line",
        category: "xAxis",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "xAxis.axisLine.lineStyle.color",
        key: "axisLineColor",
        label: "Axis Line Color",
        description: "Axis line color",
        category: "xAxis",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "xAxis.splitLine.show",
        key: "splitLineShow",
        label: "Show Split Lines",
        description: "Whether to show split lines",
        category: "xAxis",
        inputType: "boolean",
        defaultValue: false,
      },
      {
        path: "xAxis.splitLine.lineStyle.color",
        key: "splitLineColor",
        label: "Split Line Color",
        description: "Split line color",
        category: "xAxis",
        inputType: "color",
        defaultValue: "#E5E5E5",
      },
      {
        path: "xAxis.splitLine.lineStyle.type",
        key: "splitLineType",
        label: "Split Line Type",
        description: "Split line type",
        category: "xAxis",
        inputType: "enum",
        defaultValue: "solid",
        enumValues: ["solid", "dashed", "dotted"],
      },
    ],
  };
}

function yAxisCategory(): PropertyCategory {
  return {
    id: "yAxis",
    label: "Y Axis",
    icon: "axis-y",
    description: "Y axis configuration",
    properties: [
      {
        path: "yAxis.type",
        key: "type",
        label: "Type",
        description: "Y axis type",
        category: "yAxis",
        inputType: "enum",
        defaultValue: "value",
        enumValues: ["category", "value", "time", "log"],
      },
      {
        path: "yAxis.name",
        key: "name",
        label: "Name",
        description: "Y axis name",
        category: "yAxis",
        inputType: "string",
        defaultValue: "",
      },
      {
        path: "yAxis.nameLocation",
        key: "nameLocation",
        label: "Name Location",
        description: "Position of axis name",
        category: "yAxis",
        inputType: "enum",
        defaultValue: "end",
        enumValues: ["start", "middle", "end"],
      },
      {
        path: "yAxis.nameTextStyle.color",
        key: "nameColor",
        label: "Name Color",
        description: "Axis name text color",
        category: "yAxis",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "yAxis.nameGap",
        key: "nameGap",
        label: "Name Gap",
        description: "Gap between name and axis",
        category: "yAxis",
        inputType: "number",
        defaultValue: 15,
        min: 0,
        max: 50,
      },
      {
        path: "yAxis.position",
        key: "position",
        label: "Position",
        description: "Position of y axis",
        category: "yAxis",
        inputType: "enum",
        defaultValue: "left",
        enumValues: ["left", "right"],
      },
      {
        path: "yAxis.offset",
        key: "offset",
        label: "Offset",
        description: "Offset of y axis from default position",
        category: "yAxis",
        inputType: "number",
        defaultValue: 0,
        min: -100,
        max: 100,
      },
      {
        path: "yAxis.min",
        key: "min",
        label: "Min",
        description: "Minimum value of axis",
        category: "yAxis",
        inputType: "string",
        defaultValue: "auto",
      },
      {
        path: "yAxis.max",
        key: "max",
        label: "Max",
        description: "Maximum value of axis",
        category: "yAxis",
        inputType: "string",
        defaultValue: "auto",
      },
      {
        path: "yAxis.splitNumber",
        key: "splitNumber",
        label: "Split Number",
        description: "Approximate number of splits",
        category: "yAxis",
        inputType: "number",
        defaultValue: 5,
        min: 0,
        max: 20,
      },
      {
        path: "yAxis.axisLabel.show",
        key: "axisLabelShow",
        label: "Show Labels",
        description: "Whether to show axis labels",
        category: "yAxis",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "yAxis.axisLabel.color",
        key: "axisLabelColor",
        label: "Label Color",
        description: "Axis label text color",
        category: "yAxis",
        inputType: "color",
        defaultValue: "#666",
      },
      {
        path: "yAxis.axisLabel.fontSize",
        key: "axisLabelFontSize",
        label: "Label Font Size",
        description: "Axis label font size",
        category: "yAxis",
        inputType: "number",
        defaultValue: 12,
        min: 8,
        max: 24,
      },
      {
        path: "yAxis.axisLabel.rotate",
        key: "axisLabelRotate",
        label: "Label Rotate",
        description: "Axis label rotation angle",
        category: "yAxis",
        inputType: "number",
        defaultValue: 0,
        min: -90,
        max: 90,
      },
      {
        path: "yAxis.axisLine.show",
        key: "axisLineShow",
        label: "Show Axis Line",
        description: "Whether to show axis line",
        category: "yAxis",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "yAxis.axisLine.lineStyle.color",
        key: "axisLineColor",
        label: "Axis Line Color",
        description: "Axis line color",
        category: "yAxis",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "yAxis.splitLine.show",
        key: "splitLineShow",
        label: "Show Split Lines",
        description: "Whether to show split lines",
        category: "yAxis",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "yAxis.splitLine.lineStyle.color",
        key: "splitLineColor",
        label: "Split Line Color",
        description: "Split line color",
        category: "yAxis",
        inputType: "color",
        defaultValue: "#E5E5E5",
      },
      {
        path: "yAxis.splitLine.lineStyle.type",
        key: "splitLineType",
        label: "Split Line Type",
        description: "Split line type",
        category: "yAxis",
        inputType: "enum",
        defaultValue: "solid",
        enumValues: ["solid", "dashed", "dotted"],
      },
    ],
  };
}

function seriesCategory(): PropertyCategory {
  return {
    id: "series",
    label: "Series",
    icon: "chart",
    description: "Data series configuration",
    properties: [
      {
        path: "series[0].type",
        key: "type",
        label: "Chart Type",
        description: "Type of chart series",
        category: "series",
        inputType: "enum",
        defaultValue: "bar",
        enumValues: ["bar", "line", "pie", "scatter", "radar", "gauge", "funnel", "treemap", "sunburst", "sankey", "heatmap", "boxplot", "candlestick", "map", "graph", "tree"],
      },
      {
        path: "series[0].name",
        key: "name",
        label: "Name",
        description: "Series name for legend and tooltip",
        category: "series",
        inputType: "string",
        defaultValue: "",
      },
      {
        path: "series[0].data",
        key: "data",
        label: "Data",
        description: "Series data array",
        category: "series",
        inputType: "array",
        defaultValue: [],
      },
      {
        path: "series[0].smooth",
        key: "smooth",
        label: "Smooth",
        description: "Whether to show smooth curve (line/area)",
        category: "series",
        inputType: "boolean",
        defaultValue: false,
        visible: (v) => v.type === "line" || v.type === "area",
      },
      {
        path: "series[0].symbol",
        key: "symbol",
        label: "Symbol",
        description: "Symbol type for data points",
        category: "series",
        inputType: "enum",
        defaultValue: "circle",
        enumValues: ["circle", "rect", "roundRect", "triangle", "diamond", "pin", "arrow", "none"],
      },
      {
        path: "series[0].symbolSize",
        key: "symbolSize",
        label: "Symbol Size",
        description: "Size of data point symbols",
        category: "series",
        inputType: "number",
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      {
        path: "series[0].barWidth",
        key: "barWidth",
        label: "Bar Width",
        description: "Width of bar series",
        category: "series",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 100,
        visible: (v) => v.type === "bar",
      },
      {
        path: "series[0].barMaxWidth",
        key: "barMaxWidth",
        label: "Bar Max Width",
        description: "Maximum width of bar",
        category: "series",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 200,
        visible: (v) => v.type === "bar",
      },
      {
        path: "series[0].barGap",
        key: "barGap",
        label: "Bar Gap",
        description: "Gap between bars in same category",
        category: "series",
        inputType: "string",
        defaultValue: "30%",
        visible: (v) => v.type === "bar",
      },
      {
        path: "series[0].barCategoryGap",
        key: "barCategoryGap",
        label: "Category Gap",
        description: "Gap between bar categories",
        category: "series",
        inputType: "string",
        defaultValue: "20%",
        visible: (v) => v.type === "bar",
      },
      {
        path: "series[0].lineStyle.width",
        key: "lineStyleWidth",
        label: "Line Width",
        description: "Line series width",
        category: "series",
        inputType: "number",
        defaultValue: 2,
        min: 1,
        max: 20,
        visible: (v) => v.type === "line",
      },
      {
        path: "series[0].lineStyle.type",
        key: "lineStyleType",
        label: "Line Type",
        description: "Line series type",
        category: "series",
        inputType: "enum",
        defaultValue: "solid",
        enumValues: ["solid", "dashed", "dotted"],
        visible: (v) => v.type === "line",
      },
      {
        path: "series[0].lineStyle.color",
        key: "lineStyleColor",
        label: "Line Color",
        description: "Line series color",
        category: "series",
        inputType: "color",
        defaultValue: "#5470c6",
        visible: (v) => v.type === "line",
      },
      {
        path: "series[0].lineStyle.opacity",
        key: "lineStyleOpacity",
        label: "Line Opacity",
        description: "Line series opacity",
        category: "series",
        inputType: "slider",
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 0.1,
        visible: (v) => v.type === "line",
      },
      {
        path: "series[0].itemStyle.color",
        key: "itemStyleColor",
        label: "Item Color",
        description: "Item style color",
        category: "series",
        inputType: "color",
        defaultValue: "#5470c6",
      },
      {
        path: "series[0].itemStyle.borderColor",
        key: "itemStyleBorderColor",
        label: "Item Border Color",
        description: "Item border color",
        category: "series",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "series[0].itemStyle.borderWidth",
        key: "itemStyleBorderWidth",
        label: "Item Border Width",
        description: "Item border width",
        category: "series",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 10,
      },
      {
        path: "series[0].itemStyle.borderType",
        key: "itemStyleBorderType",
        label: "Item Border Type",
        description: "Item border type",
        category: "series",
        inputType: "enum",
        defaultValue: "solid",
        enumValues: ["solid", "dashed", "dotted"],
      },
      {
        path: "series[0].itemStyle.opacity",
        key: "itemStyleOpacity",
        label: "Item Opacity",
        description: "Item opacity",
        category: "series",
        inputType: "slider",
        defaultValue: 1,
        min: 0,
        max: 1,
        step: 0.1,
      },
      {
        path: "series[0].areaStyle.opacity",
        key: "areaStyleOpacity",
        label: "Area Opacity",
        description: "Area fill opacity",
        category: "series",
        inputType: "slider",
        defaultValue: 0,
        min: 0,
        max: 1,
        step: 0.1,
        visible: (v) => v.type === "line",
      },
      {
        path: "series[0].areaStyle.color",
        key: "areaStyleColor",
        label: "Area Color",
        description: "Area fill color",
        category: "series",
        inputType: "color",
        defaultValue: "rgba(84,112,198,0.5)",
        visible: (v) => v.type === "line",
      },
      {
        path: "series[0].label.show",
        key: "labelShow",
        label: "Show Label",
        description: "Whether to show data labels",
        category: "series",
        inputType: "boolean",
        defaultValue: false,
      },
      {
        path: "series[0].label.position",
        key: "labelPosition",
        label: "Label Position",
        description: "Position of data labels",
        category: "series",
        inputType: "enum",
        defaultValue: "top",
        enumValues: ["top", "left", "right", "bottom", "inside", "insideLeft", "insideRight", "insideTop", "insideBottom"],
      },
      {
        path: "series[0].label.color",
        key: "labelColor",
        label: "Label Color",
        description: "Data label text color",
        category: "series",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "series[0].label.fontSize",
        key: "labelFontSize",
        label: "Label Font Size",
        description: "Data label font size",
        category: "series",
        inputType: "number",
        defaultValue: 12,
        min: 8,
        max: 24,
      },
      {
        path: "series[0].label.formatter",
        key: "labelFormatter",
        label: "Label Formatter",
        description: "Custom label formatter (JS expression string)",
        category: "series",
        inputType: "function",
        defaultValue: undefined,
      },
      {
        path: "series[0].stack",
        key: "stack",
        label: "Stack",
        description: "Stack group name for stacked charts",
        category: "series",
        inputType: "string",
        defaultValue: "",
      },
      {
        path: "series[0].roseType",
        key: "roseType",
        label: "Rose Type",
        description: "Rose chart type (nightingale)",
        category: "series",
        inputType: "enum",
        defaultValue: "",
        enumValues: ["", "radius", "area"],
        visible: (v) => v.type === "pie",
      },
      {
        path: "series[0].radius",
        key: "radius",
        label: "Radius",
        description: "Pie chart radius (inner, outer)",
        category: "series",
        inputType: "string",
        defaultValue: "",
        visible: (v) => v.type === "pie",
      },
      {
        path: "series[0].center",
        key: "center",
        label: "Center",
        description: "Pie chart center position",
        category: "series",
        inputType: "string",
        defaultValue: "",
        visible: (v) => v.type === "pie",
      },
      {
        path: "series[0].selectedMode",
        key: "selectedMode",
        label: "Selection Mode",
        description: "Data selection mode",
        category: "series",
        inputType: "enum",
        defaultValue: "none",
        enumValues: ["none", "single", "multiple"],
      },
    ],
  };
}

function colorCategory(): PropertyCategory {
  return {
    id: "color",
    label: "Color",
    icon: "palette",
    description: "Global color palette",
    properties: [
      {
        path: "color",
        key: "palette",
        label: "Color Palette",
        description: "Global color palette for series (ordered array)",
        category: "color",
        inputType: "colorArray",
        defaultValue: [
          "#5470c6",
          "#91cc75",
          "#fac858",
          "#ee6666",
          "#73c0de",
          "#3ba272",
          "#fc8452",
          "#9a60b4",
          "#ea7ccc",
        ],
      },
    ],
  };
}

function animationCategory(): PropertyCategory {
  return {
    id: "animation",
    label: "Animation",
    icon: "play",
    description: "Animation configuration",
    properties: [
      {
        path: "animation",
        key: "enabled",
        label: "Enable Animation",
        description: "Whether to enable animation",
        category: "animation",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "animationThreshold",
        key: "threshold",
        label: "Threshold",
        description: "Maximum number for animation",
        category: "animation",
        inputType: "number",
        defaultValue: 2000,
        min: 0,
        max: 100000,
      },
      {
        path: "animationDuration",
        key: "duration",
        label: "Duration",
        description: "Animation duration in ms",
        category: "animation",
        inputType: "number",
        defaultValue: 1000,
        min: 0,
        max: 10000,
      },
      {
        path: "animationEasing",
        key: "easing",
        label: "Easing",
        description: "Animation easing function",
        category: "animation",
        inputType: "enum",
        defaultValue: "cubicOut",
        enumValues: [
          "linear",
          "quadraticIn",
          "quadraticOut",
          "quadraticInOut",
          "cubicIn",
          "cubicOut",
          "cubicInOut",
          "quarticIn",
          "quarticOut",
          "quarticInOut",
          "quinticIn",
          "quinticOut",
          "quinticInOut",
          "sinusoidalIn",
          "sinusoidalOut",
          "sinusoidalInOut",
          "exponentialIn",
          "exponentialOut",
          "exponentialInOut",
          "circularIn",
          "circularOut",
          "circularInOut",
          "elasticIn",
          "elasticOut",
          "elasticInOut",
          "backIn",
          "backOut",
          "backInOut",
          "bounceIn",
          "bounceOut",
          "bounceInOut",
        ],
      },
      {
        path: "animationDurationUpdate",
        key: "durationUpdate",
        label: "Update Duration",
        description: "Animation duration for update in ms",
        category: "animation",
        inputType: "number",
        defaultValue: 300,
        min: 0,
        max: 5000,
      },
      {
        path: "animationEasingUpdate",
        key: "easingUpdate",
        label: "Update Easing",
        description: "Easing for update animation",
        category: "animation",
        inputType: "enum",
        defaultValue: "cubicInOut",
        enumValues: [
          "linear",
          "cubicOut",
          "cubicInOut",
          "quadraticIn",
          "quadraticOut",
          "quadraticInOut",
        ],
      },
    ],
  };
}

function toolboxCategory(): PropertyCategory {
  return {
    id: "toolbox",
    label: "Toolbox",
    icon: "wrench",
    description: "Built-in toolbox features",
    properties: [
      {
        path: "toolbox.show",
        key: "show",
        label: "Show",
        description: "Whether to show the toolbox",
        category: "toolbox",
        inputType: "boolean",
        defaultValue: false,
      },
      {
        path: "toolbox.feature.saveAsImage.show",
        key: "saveAsImage",
        label: "Save as Image",
        description: "Show save as image button",
        category: "toolbox",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "toolbox.feature.saveAsImage.title",
        key: "saveAsImageTitle",
        label: "Save Image Tooltip",
        description: "Tooltip for save button",
        category: "toolbox",
        inputType: "string",
        defaultValue: "Save as Image",
      },
      {
        path: "toolbox.feature.dataZoom.show",
        key: "dataZoom",
        label: "Data Zoom",
        description: "Show data zoom button",
        category: "toolbox",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "toolbox.feature.restore.show",
        key: "restore",
        label: "Restore",
        description: "Show restore/reset button",
        category: "toolbox",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "toolbox.feature.dataView.show",
        key: "dataView",
        label: "Data View",
        description: "Show data view button",
        category: "toolbox",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "toolbox.feature.magicType.show",
        key: "magicType",
        label: "Chart Type Switch",
        description: "Show chart type switching button",
        category: "toolbox",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "toolbox.feature.magicType.type",
        key: "magicTypeTypes",
        label: "Available Types",
        description: "Types available for switching",
        category: "toolbox",
        inputType: "array",
        defaultValue: ["bar", "line"],
      },
      {
        path: "toolbox.left",
        key: "left",
        label: "Left",
        description: "Horizontal position of toolbox",
        category: "toolbox",
        inputType: "enum",
        defaultValue: "auto",
        enumValues: ["left", "center", "right", "auto"],
      },
      {
        path: "toolbox.top",
        key: "top",
        label: "Top",
        description: "Vertical position of toolbox",
        category: "toolbox",
        inputType: "enum",
        defaultValue: "auto",
        enumValues: ["top", "middle", "bottom", "auto"],
      },
    ],
  };
}

function dataZoomCategory(): PropertyCategory {
  return {
    id: "dataZoom",
    label: "Data Zoom",
    icon: "zoom",
    description: "Data zoom/scroll configuration",
    properties: [
      {
        path: "dataZoom[0].type",
        key: "type",
        label: "Type",
        description: "Type of data zoom",
        category: "dataZoom",
        inputType: "enum",
        defaultValue: "inside",
        enumValues: ["inside", "slider"],
      },
      {
        path: "dataZoom[0].show",
        key: "show",
        label: "Show",
        description: "Whether to show data zoom",
        category: "dataZoom",
        inputType: "boolean",
        defaultValue: false,
      },
      {
        path: "dataZoom[0].start",
        key: "start",
        label: "Start (%)",
        description: "Start percentage of data range",
        category: "dataZoom",
        inputType: "slider",
        defaultValue: 0,
        min: 0,
        max: 100,
      },
      {
        path: "dataZoom[0].end",
        key: "end",
        label: "End (%)",
        description: "End percentage of data range",
        category: "dataZoom",
        inputType: "slider",
        defaultValue: 100,
        min: 0,
        max: 100,
      },
      {
        path: "dataZoom[0].orient",
        key: "orient",
        label: "Orientation",
        description: "Layout orientation",
        category: "dataZoom",
        inputType: "enum",
        defaultValue: "horizontal",
        enumValues: ["horizontal", "vertical"],
      },
      {
        path: "dataZoom[0].xAxisIndex",
        key: "xAxisIndex",
        label: "X Axis Index",
        description: "Which x axis to zoom",
        category: "dataZoom",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 10,
      },
      {
        path: "dataZoom[0].yAxisIndex",
        key: "yAxisIndex",
        label: "Y Axis Index",
        description: "Which y axis to zoom",
        category: "dataZoom",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 10,
      },
      {
        path: "dataZoom[0].filterMode",
        key: "filterMode",
        label: "Filter Mode",
        description: "How filtered data is handled",
        category: "dataZoom",
        inputType: "enum",
        defaultValue: "filter",
        enumValues: ["filter", "weakFilter", "empty", "none"],
      },
      {
        path: "dataZoom[0].backgroundColor",
        key: "backgroundColor",
        label: "Background Color",
        description: "Slider background color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "rgba(47,69,84,0)",
      },
      {
        path: "dataZoom[0].dataBackground.lineStyle.color",
        key: "dataBgLineColor",
        label: "Data Background Line Color",
        description: "Data background line color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "#a0a0a0",
      },
      {
        path: "dataZoom[0].dataBackground.areaStyle.color",
        key: "dataBgAreaColor",
        label: "Data Background Area Color",
        description: "Data background area color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "#717171",
      },
      {
        path: "dataZoom[0].selectedDataBackground.lineStyle.color",
        key: "selectedBgLineColor",
        label: "Selected Background Line Color",
        description: "Selected range line color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "#5470c6",
      },
      {
        path: "dataZoom[0].selectedDataBackground.areaStyle.color",
        key: "selectedBgAreaColor",
        label: "Selected Background Area Color",
        description: "Selected range area color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "#5470c6",
      },
      {
        path: "dataZoom[0].handleStyle.color",
        key: "handleColor",
        label: "Handle Color",
        description: "Handle color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "#333",
      },
      {
        path: "dataZoom[0].fillerColor",
        key: "fillerColor",
        label: "Filler Color",
        description: "Selected area fill color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "rgba(0,0,0,0.15)",
      },
      {
        path: "dataZoom[0].borderColor",
        key: "borderColor",
        label: "Border Color",
        description: "Slider border color",
        category: "dataZoom",
        inputType: "color",
        defaultValue: "#333",
      },
    ],
  };
}

function visualMapCategory(): PropertyCategory {
  return {
    id: "visualMap",
    label: "Visual Map",
    icon: "gradient",
    description: "Visual mapping for continuous/categorical color",
    properties: [
      {
        path: "visualMap[0].type",
        key: "type",
        label: "Type",
        description: "Visual map type",
        category: "visualMap",
        inputType: "enum",
        defaultValue: "continuous",
        enumValues: ["continuous", "piecewise"],
      },
      {
        path: "visualMap[0].show",
        key: "show",
        label: "Show",
        description: "Whether to show visual map",
        category: "visualMap",
        inputType: "boolean",
        defaultValue: false,
      },
      {
        path: "visualMap[0].min",
        key: "min",
        label: "Min",
        description: "Minimum value for mapping",
        category: "visualMap",
        inputType: "number",
        defaultValue: 0,
      },
      {
        path: "visualMap[0].max",
        key: "max",
        label: "Max",
        description: "Maximum value for mapping",
        category: "visualMap",
        inputType: "number",
        defaultValue: 100,
      },
      {
        path: "visualMap[0].calculable",
        key: "calculable",
        label: "Calculable",
        description: "Whether the visual map is calculable",
        category: "visualMap",
        inputType: "boolean",
        defaultValue: true,
      },
      {
        path: "visualMap[0].orient",
        key: "orient",
        label: "Orientation",
        description: "Layout orientation",
        category: "visualMap",
        inputType: "enum",
        defaultValue: "vertical",
        enumValues: ["horizontal", "vertical"],
      },
      {
        path: "visualMap[0].left",
        key: "left",
        label: "Left",
        description: "Horizontal position",
        category: "visualMap",
        inputType: "enum",
        defaultValue: "auto",
        enumValues: ["left", "center", "right", "auto"],
      },
      {
        path: "visualMap[0].top",
        key: "top",
        label: "Top",
        description: "Vertical position",
        category: "visualMap",
        inputType: "enum",
        defaultValue: "auto",
        enumValues: ["top", "middle", "bottom", "auto"],
      },
      {
        path: "visualMap[0].inRange.color",
        key: "inRangeColor",
        label: "In Range Colors",
        description: "Color range for mapping",
        category: "visualMap",
        inputType: "colorArray",
        defaultValue: ["#50a3ba", "#eac736", "#d94e5d"],
      },
      {
        path: "visualMap[0].seriesIndex",
        key: "seriesIndex",
        label: "Series Index",
        description: "Which series to apply to",
        category: "visualMap",
        inputType: "string",
        defaultValue: "",
      },
      {
        path: "visualMap[0].dimension",
        key: "dimension",
        label: "Dimension",
        description: "Which data dimension to map",
        category: "visualMap",
        inputType: "number",
        defaultValue: 0,
        min: 0,
        max: 10,
      },
      {
        path: "visualMap[0].pieces",
        key: "pieces",
        label: "Pieces",
        description: "Custom pieces for piecewise type",
        category: "visualMap",
        inputType: "json",
        defaultValue: [],
      },
    ],
  };
}

export function getOptionSchema(): PropertyCategory[] {
  return [
    titleCategory(),
    tooltipCategory(),
    legendCategory(),
    gridCategory(),
    xAxisCategory(),
    yAxisCategory(),
    seriesCategory(),
    colorCategory(),
    animationCategory(),
    toolboxCategory(),
    dataZoomCategory(),
    visualMapCategory(),
  ];
}

export function flattenProperties(
  categories: PropertyCategory[]
): Map<string, PropertySchema> {
  const map = new Map<string, PropertySchema>();

  function walk(props: PropertySchema[]) {
    for (const prop of props) {
      map.set(prop.path, prop);
      if (prop.children) {
        walk(prop.children);
      }
    }
  }

  for (const cat of categories) {
    walk(cat.properties);
    if (cat.subcategories) {
      for (const sub of cat.subcategories) {
        walk(sub.properties);
      }
    }
  }

  return map;
}

export function getPropertyByPath(
  path: string,
  categories?: PropertyCategory[]
): PropertySchema | undefined {
  const cats = categories ?? getOptionSchema();
  const flat = flattenProperties(cats);
  return flat.get(path);
}

export function searchProperties(
  query: string,
  categories?: PropertyCategory[]
): PropertySchema[] {
  const cats = categories ?? getOptionSchema();
  const flat = flattenProperties(cats);
  const q = query.toLowerCase();

  const results: PropertySchema[] = [];
  for (const prop of flat.values()) {
    if (
      prop.label.toLowerCase().includes(q) ||
      prop.path.toLowerCase().includes(q) ||
      (prop.description && prop.description.toLowerCase().includes(q))
    ) {
      results.push(prop);
    }
  }
  return results;
}

export function getDefaultValue(
  path: string,
  categories?: PropertyCategory[]
): unknown {
  const prop = getPropertyByPath(path, categories);
  return prop?.defaultValue;
}
